// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWrG0iKq6PRpTyV5RBcUfnxzvNo1NDXN4',
    appId: '1:719134790462:web:7e6140e0c1caa176dcd26f',
    messagingSenderId: '719134790462',
    projectId: 'codetrax-8fd48',
    authDomain: 'codetrax-8fd48.firebaseapp.com',
    databaseURL: 'https://codetrax-8fd48-default-rtdb.firebaseio.com',
    storageBucket: 'codetrax-8fd48.firebasestorage.app',
    measurementId: 'G-34DK81Y99F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0KfEEEYbo2W0K-JkUFOeX_IHB3Y6zq6k',
    appId: '1:719134790462:android:dba2405e69619a5cdcd26f',
    messagingSenderId: '719134790462',
    projectId: 'codetrax-8fd48',
    databaseURL: 'https://codetrax-8fd48-default-rtdb.firebaseio.com',
    storageBucket: 'codetrax-8fd48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeH3sGp1wDhlO5ap_ATo5qYn9nEF8dRk',
    appId: '1:719134790462:ios:414d03b323994be4dcd26f',
    messagingSenderId: '719134790462',
    projectId: 'codetrax-8fd48',
    databaseURL: 'https://codetrax-8fd48-default-rtdb.firebaseio.com',
    storageBucket: 'codetrax-8fd48.firebasestorage.app',
    iosClientId: '719134790462-4ai0d9hipt6vh3s5ql2oegphemmmq6gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projrct',
  );

}